### ISSUE TITLE
Crash with XCode 16

### ISSUE THREAD

**Issue by benjdum59** [DataDome/datadome-ios-package#20] opened 2024-09-18 13:41 UTC
Hello,

My app crashed when starting (using XCode 16):

Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
Referenced from: <02F9AAC7-A5E8-383B-8D79-123D368C439E> /private/var/containers/Bundle/Application/4456AA55-0309-4F09-AA6C-A9F99D5F1A75/ThisIsATest.app/Frameworks/DataDomeAlamofire.framework/DataDomeAlamofire
Expected in: <70D3CB39-11C4-3F8E-94F7-BF9B0020C879> /private/var/containers/Bundle/Application/4456AA55-0309-4F09-AA6C-A9F99D5F1A75/ThisIsATest.app/Frameworks/Alamofire.framework/Alamofire

These are the versions I use (with Cocoapods):

Alamofire 5.9.1
DataDomeAlamofire 3.6.0
DataDomeSDK 3.6.0

**Comment by Kireyin** [comment] 2024-09-19 07:14
Closing - duplicate of https://github.com/DataDome/datadome-alamofire-package/issues/19

**Closed by Kireyin** 2024-09-19 07:14 UTC
